/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Darwin Jarvis 15.4.0 x86_64"
#define LGL_COMPILED "Thu May 12 21:28:49 CEST 2016"
#define LGL_RELEASED "Mon Nov  9 11:05:36 CET 2015"
#define LGL_VERSION "baq"
#define LGL_ID "e70d0975626ada3f714ee4ee8cce57adca9fdafd"
